"""
OAuth2 service for Google and GitHub social login.

Server-side OAuth flow:
1. Frontend redirects to /auth/oauth/{provider}/login
2. Backend redirects to provider's OAuth consent screen (with state=CSRF token)
3. Provider redirects back to /auth/oauth/{provider}/callback
4. Backend exchanges code for access token
5. Backend fetches user info (email, name) from provider
6. Backend creates/finds user by email, generates JWT
7. Backend redirects to frontend with token in query string
"""

import os
import json
import time
import secrets
import logging
import uuid
from datetime import datetime, timezone
from typing import Optional
from urllib.parse import urlencode

import httpx

from app.services.user_service import create_user, get_user_by_email
from app.services.field_encryption import email_hash, encrypt_field, decrypt_field
from app.database.config import db_config
from app.database.models import User as UserModel
from sqlalchemy import select

logger = logging.getLogger(__name__)

# ── Config ──────────────────────────────────────────────────────────────────

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")
GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID", "")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET", "")

# Frontend URL for redirect after successful OAuth
FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:5173").split(",")[0].strip(),
)

# Backend public URL for OAuth redirect URIs
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")

# OAuth state tokens are single-use CSRF tokens — they must not stay valid
# forever. 10 minutes matches the typical OAuth round-trip budget.
_STATE_TTL_SECONDS = 600
_STATE_REDIS_PREFIX = "oauth:state"

# cache_service.get_client() does not cache its *negative* result: when Redis
# is configured but unreachable, every call re-attempts a 2s connect+ping. To
# keep that from adding ~2s to every OAuth state operation while Redis is
# down, oauth_service remembers the failure and short-circuits for 30s.
# (When REDIS_URL is simply unset, get_client() returns None instantly with
# no penalty, so the backoff only affects the genuinely-bad case.)
_redis_unavailable_until: float = 0.0
_REDIS_RETRY_AFTER_SECONDS = 30

# In-memory fallback store. Redis (via cache_service) is preferred so a state
# generated by one worker can be consumed by another in multi-worker deploys;
# the dict keeps single-process deploys and tests working with zero setup.
_state_store: dict[str, dict] = {}


def _state_key(state: str) -> str:
    return f"{_STATE_REDIS_PREFIX}:{state}"


def _record_is_fresh(record: dict) -> bool:
    """True when the record's created_at is within the state TTL."""
    try:
        created = datetime.fromisoformat(record["created_at"])
    except (KeyError, ValueError, TypeError):
        return False
    return (datetime.now(timezone.utc) - created).total_seconds() <= _STATE_TTL_SECONDS


async def _redis_client():
    """Return the shared Redis client, or None when Redis is unavailable.

    Failed availability probes are remembered for 30s so a down Redis doesn't
    stall every state write/read with its connect timeout.
    """
    global _redis_unavailable_until
    now = time.monotonic()
    if now < _redis_unavailable_until:
        return None
    try:
        from app.services.cache_service import get_client

        client = await get_client()
        if client is None:
            _redis_unavailable_until = now + _REDIS_RETRY_AFTER_SECONDS
        return client
    except Exception:
        _redis_unavailable_until = now + _REDIS_RETRY_AFTER_SECONDS
        return None


async def _save_state(extra: Optional[dict] = None) -> str:
    """Persist an OAuth state record and return its opaque single-use token.

    The record carries ``extra`` fields (e.g. ``mode``/``uid`` for account
    linking) plus ``created_at`` for TTL enforcement. Redis is preferred so a
    ``/login`` state issued by worker A can be consumed by worker B; the
    in-memory dict is the fallback when Redis is not configured or fails.
    """
    state = secrets.token_urlsafe(32)
    record = {"created_at": datetime.now(timezone.utc).isoformat(), **(extra or {})}
    client = await _redis_client()
    if client is not None:
        try:
            await client.setex(_state_key(state), _STATE_TTL_SECONDS, json.dumps(record))
            return state
        except Exception:
            logger.warning(
                "OAuth state Redis write failed — using in-memory fallback", exc_info=True
            )
    _clean_expired_states()
    _state_store[state] = record
    return state


async def _consume_state(state: str) -> Optional[dict]:
    """Validate and atomically consume a state token. Returns its record, or None.

    A state token is rejected (and removed) when it was never issued, was
    already consumed, or is older than :data:`_STATE_TTL_SECONDS`. Redis
    ``GETDEL`` makes consumption atomic across workers; the in-memory dict
    serves the fallback path (including states written while Redis was down).
    """
    client = await _redis_client()
    if client is not None:
        try:
            raw = await client.getdel(_state_key(state))
        except Exception:
            logger.warning(
                "OAuth state Redis read failed — falling back to in-memory", exc_info=True
            )
            raw = None
        if raw is not None:
            try:
                record = json.loads(raw)
            except (TypeError, ValueError):
                logger.warning("Malformed OAuth state record discarded")
                return None
            if not _record_is_fresh(record):
                logger.warning(
                    "Expired OAuth state parameter (older than %ss)", _STATE_TTL_SECONDS
                )
                return None
            return record
        # Redis miss — the token may have been written to the in-memory
        # fallback while Redis was briefly unavailable.
        return _pop_memory_state(state)
    return _pop_memory_state(state)


def _pop_memory_state(state: str) -> Optional[dict]:
    """Pop a state token from the in-memory fallback store (TTL-checked)."""
    record = _state_store.pop(state, None)
    if record is None:
        logger.warning("Invalid or expired OAuth state parameter")
        return None
    if not _record_is_fresh(record):
        logger.warning("Expired OAuth state parameter (older than %ss)", _STATE_TTL_SECONDS)
        return None
    return record


def _clean_expired_states():
    """Remove in-memory fallback tokens older than ``_STATE_TTL_SECONDS``."""
    now = datetime.now(timezone.utc)
    expired = []
    for s, v in _state_store.items():
        try:
            created = datetime.fromisoformat(v["created_at"])
        except (KeyError, ValueError, TypeError):
            expired.append(s)
            continue
        if (now - created).total_seconds() > _STATE_TTL_SECONDS:
            expired.append(s)
    for s in expired:
        _state_store.pop(s, None)


# ── Google OAuth ────────────────────────────────────────────────────────────

GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"
GOOGLE_USERINFO_URL = "https://www.googleapis.com/oauth2/v2/userinfo"
GOOGLE_SCOPES = "openid email profile"


async def get_google_login_url() -> str:
    """Build the Google OAuth consent screen URL."""
    state = await _save_state()
    redirect_uri = f"{BACKEND_URL}/api/v1/auth/oauth/google/callback"
    params = {
        "client_id": GOOGLE_CLIENT_ID,
        "redirect_uri": redirect_uri,
        "response_type": "code",
        "scope": GOOGLE_SCOPES,
        "state": state,
        "access_type": "online",
        "prompt": "select_account",
    }
    return f"{GOOGLE_AUTH_URL}?{urlencode(params)}"


async def handle_google_callback(code: str, state: str) -> dict:
    """Exchange Google auth code for user info and return auth result.

    Returns a dict with 'uid', 'email', 'name', 'provider', 'token' on success,
    or raises an exception on failure.
    """
    if await _consume_state(state) is None:
        raise ValueError("Invalid state parameter. Possible CSRF attack.")

    _clean_expired_states()

    # Exchange authorization code for tokens
    redirect_uri = f"{BACKEND_URL}/api/v1/auth/oauth/google/callback"
    async with httpx.AsyncClient(timeout=15.0) as client:
        token_resp = await client.post(
            GOOGLE_TOKEN_URL,
            data={
                "code": code,
                "client_id": GOOGLE_CLIENT_ID,
                "client_secret": GOOGLE_CLIENT_SECRET,
                "redirect_uri": redirect_uri,
                "grant_type": "authorization_code",
            },
        )
        if token_resp.status_code != 200:
            logger.error("Google token exchange failed: %s", token_resp.text)
            raise ValueError("Failed to exchange authorization code with Google")

        token_data = token_resp.json()
        access_token = token_data.get("access_token")

        # Fetch user info
        user_resp = await client.get(
            GOOGLE_USERINFO_URL,
            headers={"Authorization": f"Bearer {access_token}"},
        )
        if user_resp.status_code != 200:
            logger.error("Google userinfo failed: %s", user_resp.text)
            raise ValueError("Failed to fetch user info from Google")

        user_info = user_resp.json()

    email = user_info.get("email", "")
    name = user_info.get("name", "") or email.split("@")[0]
    google_id = user_info.get("id", "")

    if not email:
        raise ValueError("Google did not provide an email address")

    return await _find_or_create_oauth_user(email, name, "google.com", google_id)


# ── GitHub OAuth ────────────────────────────────────────────────────────────

GITHUB_AUTH_URL = "https://github.com/login/oauth/authorize"
GITHUB_TOKEN_URL = "https://github.com/login/oauth/access_token"
GITHUB_USERINFO_URL = "https://api.github.com/user"
GITHUB_SCOPES = "read:user user:email"


async def get_github_login_url(mode: str = "login", uid: Optional[str] = None) -> str:
    """Build the GitHub OAuth consent screen URL.

    ``mode="link"`` (with ``uid``) starts the account-linking flow: the
    authenticated user's uid is baked into the server-side state token so the
    callback can attach the GitHub identity to their existing account instead
    of erroring on a provider mismatch. ``mode="login"`` is the default
    sign-in / sign-up flow.
    """
    extra: dict[str, str] = {"mode": mode}
    if mode == "link" and uid:
        extra["uid"] = uid
    state = await _save_state(extra)
    redirect_uri = f"{BACKEND_URL}/api/v1/auth/oauth/github/callback"
    params = {
        "client_id": GITHUB_CLIENT_ID,
        "redirect_uri": redirect_uri,
        "scope": GITHUB_SCOPES,
        "state": state,
    }
    return f"{GITHUB_AUTH_URL}?{urlencode(params)}"


async def handle_github_callback(code: str, state: str) -> dict:
    """Exchange GitHub auth code for user info and return auth result.

    Two modes, carried in the server-side state token:
      - ``login`` (default): find-or-create the account for the GitHub email.
      - ``link``: attach the GitHub identity to the authenticated account
        whose uid was baked into the state by :func:`get_github_login_url`.
    """
    state_record = await _consume_state(state)
    if state_record is None:
        raise ValueError("Invalid state parameter. Possible CSRF attack.")

    _clean_expired_states()

    # Exchange authorization code for access token
    redirect_uri = f"{BACKEND_URL}/api/v1/auth/oauth/github/callback"
    async with httpx.AsyncClient(timeout=15.0) as client:
        token_resp = await client.post(
            GITHUB_TOKEN_URL,
            data={
                "client_id": GITHUB_CLIENT_ID,
                "client_secret": GITHUB_CLIENT_SECRET,
                "code": code,
                "redirect_uri": redirect_uri,
            },
            headers={"Accept": "application/json"},
        )
        if token_resp.status_code != 200:
            logger.error("GitHub token exchange failed: %s", token_resp.text)
            raise ValueError("Failed to exchange authorization code with GitHub")

        token_data = token_resp.json()
        access_token = token_data.get("access_token")

        if not access_token:
            error_desc = token_data.get("error_description", token_data.get("error", "unknown error"))
            logger.error("GitHub token exchange no access_token: %s", error_desc)
            raise ValueError(f"GitHub OAuth error: {error_desc}")

        # Fetch user info
        user_resp = await client.get(
            GITHUB_USERINFO_URL,
            headers={
                "Authorization": f"Bearer {access_token}",
                "Accept": "application/vnd.github.v3+json",
                "User-Agent": "Onramp-2.0",
            },
        )
        if user_resp.status_code != 200:
            logger.error("GitHub userinfo failed: %s", user_resp.text)
            raise ValueError("Failed to fetch user info from GitHub")

        user_info = user_resp.json()

    # Try to get primary email
    email = user_info.get("email", "")
    name = user_info.get("name", "") or user_info.get("login", "")

    # GitHub doesn't always expose email in user endpoint
    if not email:
        # Try emails endpoint
        async with httpx.AsyncClient(timeout=15.0) as client:
            emails_resp = await client.get(
                f"{GITHUB_USERINFO_URL}/emails",
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Accept": "application/vnd.github.v3+json",
                    "User-Agent": "Onramp-2.0",
                },
            )
            if emails_resp.status_code == 200:
                emails = emails_resp.json()
                for e in emails:
                    if e.get("primary") and e.get("verified"):
                        email = e["email"]
                        break
                if not email and emails:
                    email = emails[0].get("email", "")

    if not email:
        raise ValueError("GitHub did not provide an email address. Make sure your GitHub email is public or grant email permission.")

    github_id = str(user_info.get("id", ""))
    github_username = user_info.get("login", "") or None

    # Account linking: attach the GitHub identity to the authenticated user
    # whose uid was baked into the state at /auth/oauth/github/link.
    if state_record.get("mode") == "link":
        link_uid = state_record.get("uid")
        if not link_uid:
            raise ValueError("Invalid link request — missing account reference.")
        user = await link_github_identity(link_uid, github_id, github_username, email)
        from app.api.v1.auth import _generate_jwt

        token = _generate_jwt(
            user["uid"], user["email"], user["name"], user.get("provider", "password")
        )
        return {
            "uid": user["uid"],
            "email": user["email"],
            "name": user["name"],
            "provider": user.get("provider", "password"),
            "token": token,
        }

    return await _find_or_create_oauth_user(
        email, name, "github.com", github_id, github_username=github_username
    )


# ── Account linking ─────────────────────────────────────────────────────────


async def link_github_identity(
    uid: str, github_id: str, github_username: str, github_email: str = ""
) -> dict:
    """Attach a GitHub identity (id + username) to an existing account.

    Used by the account-linking OAuth flow so users who signed up with
    email/password can connect their GitHub identity to the same account
    instead of creating a second one. The account's email/provider stay
    untouched — only ``github_id`` / ``github_username`` are written.

    Refuses to link when the GitHub email already belongs to a *different*
    account — the GitHub identity would then be ambiguous between the two,
    and the PR/issue auto-matching (which keys on github_username) would be
    unreliable.

    Uses the storage layer so it works on both the memory and PostgreSQL
    backends (unlike the ORM-only login path).

    Raises ValueError on missing/inactive accounts or invalid usernames.
    """
    from app.services.user_service import get_user_by_uid, update_user_profile

    user = await get_user_by_uid(uid)
    if user is None:
        raise ValueError("Account not found — please sign in again.")
    if not user.get("is_active", True):
        raise ValueError("Account is deactivated.")

    # A GitHub account (``github_id``) is globally unique — it must not already
    # be claimed by a *different* account, regardless of whether GitHub exposes
    # the email. Without this guard, a GitHub account with a hidden email could
    # be linked to two onramp accounts, making the github_username-based
    # PR/issue auto-matching ambiguous.
    if github_id:
        from app.services.postgres_db import get_storage

        storage = get_storage()
        claimed = await storage.query_documents(
            "users", [("github_id", "==", str(github_id))]
        )
        for other in claimed:
            other_uid = other.get("id") or other.get("uid")
            if other_uid and other_uid != uid:
                raise ValueError(
                    "This GitHub account is already linked to another account."
                )

    if github_email:
        existing = await get_user_by_email(github_email)
        if existing and existing.get("uid") != uid:
            raise ValueError(
                "This GitHub account's email is already registered to another "
                "account. Sign in with that account instead."
            )

    updates: dict = {}
    if github_id:
        updates["github_id"] = str(github_id)
    if github_username:
        updates["github_username"] = github_username
    if not updates:
        raise ValueError("GitHub did not provide an identity to link.")

    updated = await update_user_profile(uid, updates)
    if updated is None:
        raise ValueError("Account not found — please sign in again.")
    return updated


# ── Shared ──────────────────────────────────────────────────────────────────


async def _find_or_create_oauth_user(
    email: str, name: str, provider: str, provider_id: str, github_username: str | None = None
) -> dict:
    """Find existing user by email or create a new one for OAuth login.

    Uses the ORM User model directly (consistent with login() path).
    Returns a dict with 'uid', 'email', 'name', 'provider', 'token'.
    """
    from app.api.v1.auth import _generate_jwt

    await db_config.ensure_engine()
    factory = db_config.get_session_factory()

    async with factory() as session:
        result = await session.execute(
            select(UserModel).where(UserModel.email_hash == email_hash(email))
        )
        user_row = result.scalar_one_or_none()

        if user_row:
            # User exists — verify provider matches
            if user_row.provider != provider:
                raise ValueError(
                    f"This email is already registered with {user_row.provider}. "
                    f"Please sign in with {user_row.provider} instead."
                )
            if not user_row.is_active:
                raise ValueError("Account is deactivated")

            uid = user_row.id
            raw_email = user_row.email
            raw_name = user_row.name
            if raw_email.startswith("gAAAAA"):
                raw_email = decrypt_field(raw_email)
                raw_name = decrypt_field(raw_name)

            # Sync GitHub identity on every GitHub sign-in so username changes
            # propagate and the column is backfilled for existing accounts.
            if github_username:
                changed = False
                if user_row.github_username != github_username:
                    user_row.github_username = github_username
                    user_row.updated_at = datetime.now(timezone.utc)
                    changed = True
                if provider_id and user_row.github_id != provider_id:
                    user_row.github_id = provider_id
                    changed = True
                if changed:
                    session.add(user_row)
        else:
            # Create new user
            uid = str(uuid.uuid4())
            now = datetime.now(timezone.utc)
            hashed_email = encrypt_field(email)
            hashed_name = encrypt_field(name)

            new_user = UserModel(
                id=uid,
                email=hashed_email,
                email_hash=email_hash(email),
                name=hashed_name,
                provider=provider,
                is_active=True,
                is_admin=False,
                created_at=now,
                updated_at=now,
                last_login_at=now,
                github_username=github_username if provider == "github.com" else None,
                github_id=(provider_id if provider == "github.com" else None),
            )
            session.add(new_user)
            await session.flush()
            raw_email = email
            raw_name = name

        # Persist the new user / last-login update. Without this commit the
        # session rolls back on block exit and the OAuth user is never saved,
        # so the issued token points at a uid that doesn't exist.
        await session.commit()

    token = _generate_jwt(uid, raw_email, raw_name, provider)
    return {
        "uid": uid,
        "email": raw_email,
        "name": raw_name,
        "provider": provider,
        "token": token,
    }
