from typing import Dict, Any


class ReportGenerator:
    async def generate_html(self, report_data: Dict[str, Any]) -> str:
        repo = report_data.get("repo", "unknown")
        sections = report_data.get("report", [])

        html = [
            "<!DOCTYPE html><html><head><meta charset='utf-8'>",
            f"<title>Onboarding Report - {repo}</title>",
            "<style>",
            "body{font-family:-apple-system,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#333;line-height:1.6}",
            "h1{color:#1a1a2e;border-bottom:2px solid #e94560;padding-bottom:8px}",
            "h2{color:#16213e;margin-top:32px}",
            ".module{background:#f8f9fa;border-left:3px solid #4361ee;padding:12px 16px;margin:12px 0;border-radius:0 8px 8px 0}",
            ".module h3{margin:0 0 4px;color:#4361ee}",
            ".module p{margin:0;color:#666;font-size:14px}",
            ".stat{display:inline-block;background:#e94560;color:white;padding:4px 12px;border-radius:20px;font-size:14px;margin:4px}",
            "ul{color:#555}",
            "footer{margin-top:48px;padding-top:16px;border-top:1px solid #eee;color:#999;font-size:13px}",
            ".faq-item{border-bottom:1px solid #eee;padding:8px 0}",
            ".faq-q{font-weight:600;color:#16213e}",
            ".faq-a{color:#555;margin-top:4px}",
            "</style></head><body>",
            f"<h1>Onboarding Report: {repo}</h1>",
        ]

        for section in sections:
            html.append(f"<h2>{section.get('title', '')}</h2>")
            content = section.get("content", {})
            stype = section.get("type", "")

            if stype == "overview":
                html.append(f"<p>Repository: {content.get('repo', '')}</p>")
                html.append(f"<p>Difficulty: <span class='stat'>{content.get('user_level', '')}</span></p>")

            elif stype == "modules":
                for mod in content.get("modules", []):
                    html.append(f"<div class='module'>")
                    html.append(f"<h3>{mod.get('name', '')}</h3>")
                    html.append(f"<p>Estimated: {mod.get('time', '?')} hours</p>")
                    items = mod.get("items", [])
                    if items:
                        html.append("<ul>")
                        for item in items:
                            html.append(f"<li>{item}</li>")
                        html.append("</ul>")
                    html.append("</div>")

            elif stype == "faq":
                for qa in content.get("questions", []):
                    html.append("<div class='faq-item'>")
                    html.append(f"<div class='faq-q'>Q: {qa.get('q', '')}</div>")
                    html.append(f"<div class='faq-a'>A: {qa.get('a', '')}</div>")
                    html.append("</div>")

            elif stype == "summary":
                html.append(f"<p>Total estimated onboarding time: <strong>{content.get('total_hours', '?')} hours</strong></p>")
                html.append(f"<p>Difficulty level: {content.get('difficulty', '?')}</p>")

            else:
                note = content.get("note", "")
                if note:
                    html.append(f"<p><em>{note}</em></p>")

        html.append("<footer>Generated by Onramp 2.0</footer>")
        html.append("</body></html>")
        return "\n".join(html)
