"""reconcile schema - add dynamic_documents table

Revision ID: 002_reconcile_schema
Revises: initial
Create Date: 2026-06-27 00:00:00.000000

NOTE: This migration was manually generated by diffing the 001_initial_schema
migration against the current SQLAlchemy models (models.py).

Schema drift found:
  - dynamic_documents table was never created by any migration

All other tables (users, teams, team_members, api_keys, usage_records)
are in sync between 001_initial_schema and the current models.

Verify against a real database before applying to production.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = '002_reconcile_schema'
down_revision: Union[str, None] = 'initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create dynamic_documents table - missing from 001_initial_schema
    # Fallback/generic collection store for unmigrated Firestore collections
    op.create_table('dynamic_documents',
        sa.Column('id', sa.String(length=255), nullable=False),
        sa.Column('collection', sa.String(length=255), nullable=False),
        sa.Column('data', JSONB(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id', 'collection'),
    )
    op.create_index(
        'ix_dynamic_documents_collection',
        'dynamic_documents',
        ['collection'],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index('ix_dynamic_documents_collection', table_name='dynamic_documents')
    op.drop_table('dynamic_documents')
