"""add onboarding tables

Revision ID: d63ba1e4a029
Revises: d82af5364a0c
Create Date: 2026-07-27 13:48:34.496051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63ba1e4a029'
down_revision: Union[str, None] = 'd82af5364a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_plans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('buddy_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'completed', 'cancelled')", name='ck_onboarding_plan_status'),
    sa.ForeignKeyConstraint(['buddy_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_plans', schema=None) as batch_op:
        batch_op.create_index('ix_onboarding_plans_team', ['team_id'], unique=False)
        batch_op.create_index('ix_onboarding_plans_user', ['user_id'], unique=False)

    op.create_table('onboarding_milestones',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('day_target', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('technical', 'cultural', 'process', 'product', 'social')", name='ck_milestone_category'),
    sa.CheckConstraint('day_target IN (30, 60, 90)', name='ck_milestone_day_target'),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_milestones', schema=None) as batch_op:
        batch_op.create_index('ix_onboarding_milestones_plan', ['plan_id'], unique=False)

    op.create_table('pre_boarding_tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("assignee IN ('developer', 'hr', 'it', 'manager', 'buddy')", name='ck_preboarding_assignee'),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pre_boarding_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_preboarding_plan', ['plan_id'], unique=False)

    op.create_table('pulse_surveys',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('clarity_score', sa.Integer(), nullable=True),
    sa.Column('support_score', sa.Integer(), nullable=True),
    sa.Column('workload_score', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('open_feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("sentiment IN ('very_happy', 'happy', 'neutral', 'frustrated', 'very_frustrated')", name='ck_pulse_sentiment'),
    sa.CheckConstraint('clarity_score BETWEEN 1 AND 10', name='ck_pulse_clarity'),
    sa.CheckConstraint('confidence_score BETWEEN 1 AND 10', name='ck_pulse_confidence'),
    sa.CheckConstraint('support_score BETWEEN 1 AND 10', name='ck_pulse_support'),
    sa.CheckConstraint('workload_score BETWEEN 1 AND 10', name='ck_pulse_workload'),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'week_number', name='uq_pulse_week')
    )
    with op.batch_alter_table('pulse_surveys', schema=None) as batch_op:
        batch_op.create_index('ix_pulse_surveys_plan', ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pulse_surveys', schema=None) as batch_op:
        batch_op.drop_index('ix_pulse_surveys_plan')

    op.drop_table('pulse_surveys')
    with op.batch_alter_table('pre_boarding_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_preboarding_plan')

    op.drop_table('pre_boarding_tasks')
    with op.batch_alter_table('onboarding_milestones', schema=None) as batch_op:
        batch_op.drop_index('ix_onboarding_milestones_plan')

    op.drop_table('onboarding_milestones')
    with op.batch_alter_table('onboarding_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_onboarding_plans_user')
        batch_op.drop_index('ix_onboarding_plans_team')

    op.drop_table('onboarding_plans')
    # ### end Alembic commands ###