"""sync models with schema

Revision ID: d82af5364a0c
Revises: 011_feature_flags_roast_mode
Create Date: 2026-07-27 13:05:43.396817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82af5364a0c'
down_revision: Union[str, None] = '011_feature_flags_roast_mode'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('member_modules', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('onramp_audit_log', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('onramp_gamification_badges', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('xp_bonus',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('onramp_gamification_streaks', schema=None) as batch_op:
        batch_op.alter_column('current_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('longest_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('streak_frozen',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    with op.batch_alter_table('onramp_learning_paths', schema=None) as batch_op:
        batch_op.alter_column('repo_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('user_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('onramp_notification_preferences', schema=None) as batch_op:
        batch_op.alter_column('digest_frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('quiet_hours_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('quiet_hours_start',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('quiet_hours_end',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('email_digest_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('onramp_notifications', schema=None) as batch_op:
        batch_op.alter_column('read',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('onramp_playbooks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('use_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('onramp_quiz_results', schema=None) as batch_op:
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('passed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('onramp_quizzes', schema=None) as batch_op:
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('onramp_subscriptions', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('billing_cycle',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    with op.batch_alter_table('onramp_tasks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('repo_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('product_signoff',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('onramp_webhook_deliveries', schema=None) as batch_op:
        batch_op.alter_column('retry_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('onramp_webhooks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('delivery_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('failure_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('onramp_webhooks', schema=None) as batch_op:
        batch_op.alter_column('failure_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('delivery_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('onramp_webhook_deliveries', schema=None) as batch_op:
        batch_op.alter_column('retry_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('onramp_tasks', schema=None) as batch_op:
        batch_op.alter_column('product_signoff',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('repo_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('onramp_subscriptions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('billing_cycle',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('onramp_quizzes', schema=None) as batch_op:
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('onramp_quiz_results', schema=None) as batch_op:
        batch_op.alter_column('passed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('onramp_playbooks', schema=None) as batch_op:
        batch_op.alter_column('use_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('onramp_notifications', schema=None) as batch_op:
        batch_op.alter_column('read',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('onramp_notification_preferences', schema=None) as batch_op:
        batch_op.alter_column('email_digest_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('quiet_hours_end',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('quiet_hours_start',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('quiet_hours_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('digest_frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('onramp_learning_paths', schema=None) as batch_op:
        batch_op.alter_column('user_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('repo_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    with op.batch_alter_table('onramp_gamification_streaks', schema=None) as batch_op:
        batch_op.alter_column('streak_frozen',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('longest_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('current_streak',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('onramp_gamification_badges', schema=None) as batch_op:
        batch_op.alter_column('xp_bonus',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('onramp_audit_log', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('member_modules', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###