apiVersion: v1
kind: Service
metadata:
  name: codeflow-backend
  labels:
    app: codeflow
    component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: codeflow
    component: backend
