import LegalLayout, { type LegalSection } from '../components/layout/LegalLayout'

const sections: LegalSection[] = [
  {
    heading: 'Information we collect',
    paragraphs: [
      'We collect information you provide directly and information generated by your use of CodeFlow.',
    ],
    bullets: [
      'Account data: name, email address, and password hash when you register (authentication is handled by Neon Auth).',
      'Team data: team names, member roles, invitations you send, and playbooks you create.',
      'Repository data: repository URLs you connect and code snippets you submit for analysis. We process code to generate answers, learning paths, and reviews; we do not use your code to train AI models.',
      'Usage data: API requests, token consumption, feature usage, and billing events, used for quota enforcement and product analytics.',
      'Payment data: handled by Stripe. We never store full card numbers on our servers.',
    ],
  },
  {
    heading: 'How we use your information',
    paragraphs: [],
    bullets: [
      'Provide, operate, and improve the CodeFlow service.',
      'Send transactional email such as team invites, digests, and billing receipts.',
      'Enforce plan quotas and rate limits.',
      'Detect abuse and secure the platform.',
      'Comply with legal obligations.',
    ],
  },
  {
    heading: 'AI processing',
    paragraphs: [
      'Questions you ask and code you submit are sent to third-party large language model providers (such as OpenRouter, Google, Groq, NVIDIA, OpenAI, or Anthropic) to generate responses. We send only the minimum context required for the request. Provider selection may change based on availability; all providers are bound by their own data processing terms, and we configure providers not to retain or train on submitted content where such controls are offered.',
    ],
  },
  {
    heading: 'Sharing',
    paragraphs: [
      'We do not sell your personal information. We share data only with service providers necessary to run CodeFlow: cloud hosting, PostgreSQL database hosting (Neon), payment processing (Stripe), email delivery, error monitoring (Sentry, configured without personally identifiable information), and the LLM providers described above. We may disclose information if required by law.',
    ],
  },
  {
    heading: 'Data retention and deletion',
    paragraphs: [
      'Account and team data are retained while your account is active. You may request deletion of your account and associated data at any time by contacting privacy@codeflow.ai; we complete verified deletion requests within 30 days. Backups expire on a rolling schedule.',
    ],
  },
  {
    heading: 'Security',
    paragraphs: [
      'Data is encrypted in transit (TLS) and at rest. GitHub tokens are encrypted with a dedicated key before storage. Access to production systems is limited and logged. No method of transmission or storage is 100% secure; we cannot guarantee absolute security.',
    ],
  },
  {
    heading: 'Cookies',
    paragraphs: [
      'We use strictly necessary cookies for authentication sessions and a small set of analytics events to understand product usage. We do not use third-party advertising cookies.',
    ],
  },
  {
    heading: 'Your rights',
    paragraphs: [
      'Depending on your jurisdiction (including the EU/EEA under GDPR and California under CCPA), you may have rights to access, correct, export, or delete your personal data, and to object to or restrict certain processing. To exercise these rights, email privacy@codeflow.ai. You may also lodge a complaint with your local supervisory authority.',
    ],
  },
  {
    heading: 'Children',
    paragraphs: [
      'CodeFlow is not directed at children under 16, and we do not knowingly collect data from them.',
    ],
  },
  {
    heading: 'Changes to this policy',
    paragraphs: [
      'We will post any changes on this page and update the date above. Material changes will be announced by email or in-app notice before they take effect.',
    ],
  },
]

export default function PrivacyPage() {
  return (
    <LegalLayout
      label="Legal"
      title="Privacy Policy"
      lastUpdated="July 2, 2026"
      intro="This policy explains what information CodeFlow collects, how we use it, and the choices you have. It applies to the CodeFlow web application, API, and SDK."
      sections={sections}
    />
  )
}
