import os
import time
import logging
from fastapi import Request
from starlette.middleware.base import BaseHTTPMiddleware

logger = logging.getLogger("onramp")
_ENV = os.getenv("ENV", "development")

class LoggingMiddleware(BaseHTTPMiddleware):
    """Logs every request with structured fields and a correlation ID.

    The correlation ID is generated by MetricsMiddleware (or this middleware,
    when metrics are disabled) and echoed back to the client via the
    ``X-Request-ID`` response header so failures can be traced end-to-end.
    """

    async def dispatch(self, request: Request, call_next):
        start_time = time.time()

        # Correlation ID — reuse the one MetricsMiddleware generated, or
        # generate + store one here (when metrics are disabled).
        request_id = getattr(request.state, "request_id", None)
        if not request_id:
            request_id = request.headers.get("X-Request-ID", "req_generate")
            request.state.request_id = request_id

        user_id = None
        try:
            user = getattr(request.state, "user", None) or {}
            user_id = user.get("uid") if isinstance(user, dict) else None
        except Exception:
            pass

        try:
            response = await call_next(request)
            process_time = (time.time() - start_time) * 1000

            logger.info(
                "method=%s path=%s status=%s duration=%.2fms "
                "ip=%s request_id=%s user=%s",
                request.method, request.url.path, response.status_code,
                process_time,
                request.client.host if request.client else "unknown",
                request_id, user_id or "-",
                extra={"request_id": request_id, "user_id": user_id},
            )

            # Only expose timing in non-production to avoid leaking
            # internal performance characteristics to attackers.
            if _ENV != "production":
                response.headers["X-Process-Time"] = f"{process_time:.2f}ms"
            response.headers.setdefault("X-Request-ID", request_id)
            return response

        except Exception as e:
            process_time = (time.time() - start_time) * 1000
            logger.error(
                "method=%s path=%s status=500 duration=%.2fms "
                "ip=%s request_id=%s error='%s'",
                request.method, request.url.path, process_time,
                request.client.host if request.client else "unknown",
                request_id, str(e),
                exc_info=True,
                extra={"request_id": request_id},
            )
            raise
